import '../styles/global.css'
import Head from 'next/head'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
    <head>
      <link rel='icon' href='/favicon.ico'/>
      <title>Tower of Hanoi Simulator</title>
    </head>
            
      <body>{children}</body>
    </html>
  )
}
